### ISSUE TITLE
Typo in repo's About section

### ISSUE THREAD

**Issue by DiegoSanchezE** [ecureuill/zombieplus-robot#1]
# Description:

Trivial bug: _Tobot_, instead of _Robot_, in the About section of the repo.
![image](https://github.com/ecureuill/zombieplus-robot/assets/20429054/8aae1785-3c23-4b5f-9b2d-8cf6093a3022)

Great job on your readme!

**Comment by ecureuill** [comment]
Hey, thanks for the heads up!
